### ISSUE TITLE
Spacing error: README.md not rendering headings properly. 

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/automated-testing#72]
Link : https://github.com/systers/automated-testing/tree/develop/PCSAWebTests
<img width="955" alt="screen shot 2017-03-29 at 22 10 57" src="https://cloud.githubusercontent.com/assets/13470643/24466074/298f1ea4-14cd-11e7-8548-f8fd8f5a4be9.png">

Can I fix this ? @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
Sure. Please go ahead.
