### ISSUE TITLE
Write redirection tests for MACC

### ISSUE THREAD

**Issue by khushbuparakh** [systers/automated-testing#88]
Testing if the page has redirected to the desired url. In my MACC django app, There is an authentication system. So, If we do not log in and try to access some profile's personal info, I get redirected to a login page.
Asserts that the response returned a status_code redirect status, redirected to expected_url (including any GET data), and that the final page was received with target_status_code.
Simulate GET and POST requests on a URL and observe the response – everything from low-level HTTP (result headers and status codes) to page content.
See the chain of redirects (if any) and check the URL and status code at each step.
Test that a given request is rendered by a given Django template, with a template context that contains certain values.
Use Django’s test client to establish that the correct template is being rendered and that the template is passed the correct context data.
Use in-browser frameworks like Selenium to test rendered HTML and the behavior of Web pages, namely JavaScript functionality. Django also provides special support for those frameworks; see the section on LiveServerTestCase for more details.

**Comment by mish24** [comment]
@khushbuparakh Done!
